// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:583034955555:web:05099c7a8f2fbaddf70e96',
    messagingSenderId: '583034955555',
    projectId: 'marine-checklist-36b30',
    authDomain: 'marine-checklist-36b30.firebaseapp.com',
    storageBucket: 'marine-checklist-36b30.firebasestorage.app',
    measurementId: 'G-FBLNLFC3VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:583034955555:android:da11a569580b07b8f70e96',
    messagingSenderId: '583034955555',
    projectId: 'marine-checklist-36b30',
    storageBucket: 'marine-checklist-36b30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:583034955555:ios:e660af5546ab9038f70e96',
    messagingSenderId: '583034955555',
    projectId: 'marine-checklist-36b30',
    storageBucket: 'marine-checklist-36b30.firebasestorage.app',
    iosBundleId: 'com.example.marineChecklistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:583034955555:ios:e660af5546ab9038f70e96',
    messagingSenderId: '583034955555',
    projectId: 'marine-checklist-36b30',
    storageBucket: 'marine-checklist-36b30.firebasestorage.app',
    iosBundleId: 'com.example.marineChecklistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:583034955555:web:5af1c2701bfe90e6f70e96',
    messagingSenderId: '583034955555',
    projectId: 'marine-checklist-36b30',
    authDomain: 'marine-checklist-36b30.firebaseapp.com',
    storageBucket: 'marine-checklist-36b30.firebasestorage.app',
    measurementId: 'G-JNBCN1LLRM',
  );
}
